#单机版

#server:
#  port: 7001
#
#
#eureka:
#  instance:
#    hostname: localhost #eureka服务端实例名称
#  client:
##    false表示不向注册中心注册自己
#    register-with-eureka: false
##    false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    fetch-registry: false
#    service-url:
##     设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



#集群版
server:
  port: 7001

eureka:
  server:
#    eureka自我保护默认开启 改成禁用
    enable-self-preservation: false
#    心跳时间
    eviction-interval-timer-in-ms: 2000
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
#    false表示不向注册中心注册自己
    register-with-eureka: false
#    false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
#     设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/

#spring:
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access: false
#  mvc:
#    servlet:
#      path: eureka
